# %YAML 1.2
# %TAG ! tag:fawkesrobotics.org,cfg/

clips_manager:
  ros__parameters:
    environments: ["main", "oneshot"]
    main:
      plugins: ["executive",
                "std_string_msg",
                "std_srvs_set_bool",
                "example_interfaces_fibonacci",
                "clips_pddl_parser",
                "config",
                "protobuf",
                "files"]
      log_clips_to_file: true
      watch: ["facts", "rules"]
    oneshot:
      log_clips_to_file: false

    protobuf:
      plugin: "cx::ProtobufPlugin"
    config:
      plugin: "cx::ConfigPlugin"
    clips_pddl_parser:
      plugin: "cx::PddlParserPlugin"
    std_string_msg:
      plugin: "cx::CXStdMsgsStringPlugin"
    std_srvs_set_bool:
      plugin: "cx::CXStdSrvsSetBoolPlugin"
    example_interfaces_fibonacci:
      plugin: "cx::CXExampleInterfacesFibonacciPlugin"
    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10
    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_bringup", "cx_goal_reasoning"]
      files: [
        "clips/cx_goal_reasoning/saliences.clp",
        "clips/cx_goal_reasoning/utils.clp",
        "clips/cx_goal_reasoning/plan.clp",
        "clips/cx_goal_reasoning/goal.clp",
        "clips/cx_goal_reasoning/domain.clp",
        "clips/cx_goal_reasoning/worldmodel.clp",
        "clips/cx_goal_reasoning/wm-domain-sync.clp",
        "clips/simple_agent/domain.clp",
        "clips/simple_agent/goal-reasoner.clp",
        "clips/simple_agent/fixed-sequence.clp",
        "clips/simple_agent/action-selection.clp",
        "clips/simple_agent/print-action.clp",
        "clips/simple_agent/refbox-comm-init.clp",
        "clips/simple_agent/ros-comm-init.clp"]
      cleanup_files: ["clips/simple_agent/mydestroy.clp"]
    files2:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_bringup"]
      files: ["clips/simple_agent/myinit2.clp"]
