clips_features_manager:
  ros__parameters:
    clips_features_list: ["clips_pddl_parser", "skill_execution", "clips_protobuf"]
    clips_features:
      mock_feature:
        plugin: "cx::MockFeature"
      plansys2:
        plugin: "cx::Plansys2Feature"
      clips_pddl_parser:
        plugin: "cx::PddlParserFeature"
      skill_execution:
        plugin: "cx::SkillExecutionFeature"
      clips_protobuf:
        plugin: "cx::ProtobufFeature"
        feature_parameters: ["protobuf_path"]
        protobuf_path:
          # This path assumes relativeness to agent_dir
          value: "proto"
          type: "string"
