clips_features_manager:
  ros__parameters:
    clips_features_list: ["clips_pddl_parser", "skill_execution", "clips_protobuf", "cx_std_msgs_string_feature", "cx_std_srvs_set_bool_feature", "cx_example_interfaces_fibonacci_feature"]
    clips_features:
      mock_feature:
        plugin: "cx::MockFeature"
      plansys2:
        plugin: "cx::Plansys2Feature"
      clips_pddl_parser:
        plugin: "cx::PddlParserFeature"
      skill_execution:
        plugin: "cx::SkillExecutionFeature"
      cx_std_msgs_string_feature:
        plugin: "cx::CXStdMsgsStringFeature"
      cx_std_srvs_set_bool_feature:
        plugin: "cx::CXStdSrvsSetBoolFeature"
      cx_example_interfaces_fibonacci_feature:
        plugin: "cx::CXExampleInterfacesFibonacciFeature"
      clips_protobuf:
        plugin: "cx::ProtobufFeature"
        feature_parameters: ["protobuf_path"]
        protobuf_path:
          # This path assumes relativeness to agent_dir
          value: "proto"
          type: "string"
