clips_features_manager:
  ros__parameters:
    clips_features: ["mock_feature", "plansys2"]

    mock_feature:
      plugin: "cx::MockFeature"
    plansys2:
      plugin: "cx::Plansys2Feature"

cx_clips:
  ros__parameters:
    alpha1: 0.2
