clips_manager:
  ros__parameters:
    environments: ["example_ros_msgs"]
    example_ros_msgs:
      plugins: ["executive", # for continuous execution
                "ros_msg", # for example topic
                "files"] # to load the CLIPS code
      log_clips_to_file: true
      watch: ["facts", "rules"]

    skill_execution:
      plugin: "cx::SkillExecutionPlugin"
    ros_msg:
      plugin: "cx::RosMsgsPlugin"
    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10

    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cx_bringup"]
      files: [
        "clips/ros_bindings/ros-msgs-introspection.clp"]
      cleanup_files: ["clips/ros_bindings/ros-msgs-introspection-cleanup.clp"]
