clips_manager:
  ros__parameters:
    environments: ["main"]
    main:
        plugins: ["executive",
                  "clips_pddl_parser",
                  "ament_index",
                  "config",
                  "create_rl_env_state",
                  "exec_action_selection",
                  "get_observable_objects",
                  "get_observable_predicates",
                  "get_predefined_observables",
                  "get_action_list",
                  "get_action_list_robot",
                  "set_rl_mode",
                  "get_free_robot",
                  "action_selection",
                  "reset_cx",
                  "files"]
        log_clips_to_file: true
        watch: ["facts", "rules"]
        redirect_stdout_to_debug: true

    ament_index:
      plugin: "cx::AmentIndexPlugin"
    
    config:
      plugin: "cx::ConfigPlugin"

    clips_pddl_parser:
      plugin: "cx::PddlParserPlugin"

    executive:
      plugin: "cx::ExecutivePlugin"
      publish_on_refresh: false
      assert_time: true
      refresh_rate: 10
    
    create_rl_env_state:
      plugin: "cx::CXCxRlInterfacesCreateRLEnvStatePlugin"

    exec_action_selection:
      plugin: "cx::CXCxRlInterfacesExecActionSelectionPlugin"

    get_observable_objects:
      plugin: "cx::CXCxRlInterfacesGetObservableObjectsPlugin"
    
    get_observable_predicates:
      plugin: "cx::CXCxRlInterfacesGetObservablePredicatesPlugin"

    get_predefined_observables:
      plugin: "cx::CXCxRlInterfacesGetPredefinedObservablesPlugin"

    get_action_list:
      plugin: "cx::CXCxRlInterfacesGetActionListPlugin"

    get_action_list_robot:
      plugin: "cx::CXCxRlInterfacesGetActionListRobotPlugin"

    set_rl_mode:
      plugin: "cx::CXCxRlInterfacesSetRLModePlugin"

    get_free_robot:
      plugin: "cx::CXCxRlInterfacesGetFreeRobotPlugin"

    action_selection:
      plugin: "cx::CXCxRlInterfacesActionSelectionPlugin"

    reset_cx:
      plugin: "cx::CXCxRlInterfacesResetCXPlugin"

    files:
      plugin: "cx::FileLoadPlugin"
      pkg_share_dirs: ["cxrl_example_agent", "cx_goal_reasoning", "cx_reinforcement_learning_plugin"]
      load: [
        "clips/blocksworld-agent/point-mapping.clp",
        "clips/cx_goal_reasoning/plan.clp",
        "clips/cx_goal_reasoning/goal.clp",
        "clips/cx_goal_reasoning/goal-tree.clp",
        "clips/cx_goal_reasoning/pddl-action.clp",
        "clips/cx_goal_reasoning/action-selection/sequential.clp",
        "clips/rl_plugin/reinforcementlearning.clp",
        "clips/rl_plugin/reset-game.clp",
        "clips/rl_plugin/rl-utils.clp",
        "clips/rl_plugin/create-rl-env-state-srv.clp",
        "clips/rl_plugin/exec-action-selection-client.clp",
        "clips/rl_plugin/get-observable-objects-srv.clp",
        "clips/rl_plugin/get-observable-predicates-srv.clp",
        "clips/rl_plugin/get-predefined-observables-srv.clp",
        "clips/rl_plugin/get-action-list-srv.clp",
        "clips/rl_plugin/get-action-list-robot-srv.clp",
        "clips/rl_plugin/set-rl-mode-srv.clp",
        "clips/rl_plugin/get-free-robot-action.clp",
        "clips/rl_plugin/action-selection-action.clp",
        "clips/rl_plugin/reset-cx-action.clp",
        "clips/blocksworld-agent/init.clp",
        "clips/blocksworld-agent/goal-production.clp",
        "clips/blocksworld-agent/goal-expansion.clp",
        "clips/blocksworld-agent/goal-executability.clp"
        ]


        
