name: ROS Build & Pre-commit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    container:
      image: quay.io/carologistics/clips_executive_base_image:kilted
      options: --user 1001 --workdir /ros_ws
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fix git refs for gitlint
        run: |
          git fetch origin +refs/heads/*:refs/remotes/origin/*
          git remote set-head origin --auto || true

      - name: Run pre-commit hooks
        run: |
          ls -lha
          . /opt/ros/kilted/setup.sh
          pre-commit run --all-files --hook-stage manual

  ros-build:
    runs-on: ubuntu-24.04
    needs: pre-commit
    strategy:
      matrix:
        ros_distro: [humble, jazzy, kilted]
    container:
      image: quay.io/carologistics/clips_executive_base_image:${{ matrix.ros_distro }}
      options: --user 1001 --workdir /ros_ws
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build ROS workspace
        run: |
          set -e
          export ROS_DISTRO=${{ matrix.ros_distro }}
          echo "Building workspace for $ROS_DISTRO"
          . /opt/ros/$ROS_DISTRO/setup.sh
          colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=OFF
